openapi: 3.0.0
info:
  title: Scissor API
  description: API documentation for the Scissor URL shortener and QR code generator
  version: 1.0.0

servers:
  - url: http://localhost:5001
    description: Local development server

paths:
  /api/urls/shorten:
    post:
      summary: Shorten a URL
      requestBody:
        description: URL to be shortened
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                originalUrl:
                  type: string
                  format: uri
                  description: The URL to shorten
      responses:
        '201':
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortenedUrl:
                    type: string
                    description: The shortened URL
        '500':
          description: Failed to shorten URL

  /api/urls/{shortId}:
    get:
      summary: Redirect to original URL
      parameters:
        - in: path
          name: shortId
          required: true
          schema:
            type: string
          description: The ID of the shortened URL
      responses:
        '302':
          description: Redirects to the original URL
        '404':
          description: URL not found
        '500':
          description: Internal server error

  /api/qrcodes:
    post:
      summary: Generate a QR code
      requestBody:
        description: URL to generate a QR code for
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: The URL to generate a QR code for
      responses:
        '200':
          description: Successfully generated QR code
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrCodeData:
                    type: string
                    description: Data URL of the generated QR code
        '500':
          description: Failed to generate QR code

  /api/analytics/clicks:
    get:
      summary: Retrieve click data
      responses:
        '200':
          description: Successfully retrieved click data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    urlId:
                      type: string
                      description: URL ID
                    timestamp:
                      type: string
                      format: date-time
                      description: Time of click
                    location:
                      type: string
                      description: Location of click
        '500':
          description: Failed to retrieve analytics data

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message